---
#- name: Add creat security
 #  azure_rm_securitygroup:
 #       resource_group: rgansible
 #       name: ng5
 #       rules: 
 #        - name : SSH
 #          protocol: Tcp
 #          destination_port_range: 22
 #          access: Allow
 #          priority: 101
 #          direction: Inbound
- debug:
        msg: "System  has uuid "
- name: remove storage
  azure_rm_storageaccount:
       resource_group: rgansible
       name: storaccrgansible
       state: absent
