---
- hosts: localhost
  gather_facts: False
  roles:
   - nic
  tasks:
   - name: Add creat security group that allows SSH
     azure_rm_securitygroup:
       resource_group: "{{ansible_rg}}"
       name: ng9
       rules: 
        - name : SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound 
